### Deployment template
apiVersion: apps/v1 # api
kind: Deployment # deployment tipini secme
metadata:
  name: firstdeployment # isim verme
  labels: # label verme
    team: development
spec: # 
  replicas: 3 # pod sayisi
  selector: # deployment objecti hangi podlar bana ait bilgisini selector altindaki labellerle yapar.
    matchLabels:
      app: frontend
  template: # podlarin ozelliklerini belirledigimiz yer
  # bundan sonraki kisim podun metadata'dan sonrasi ile ayni.
  # Sadece name yok.
    metadata:
      labels:
        app: frontend # eslesme saglandi. selectorda bulunan labeller burda da olmali tam eslesme icin.
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
### Rollout ve Rollback
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rcdeployment
  labels:
    team: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recreate
  strategy:
    type: Recreate #rollout stratejisi belirlenir deployment objecti update edildiginde.
    # Iki adet var. Recreate: tum podlar silindikten sonra yenilerini acmaya baslar. Bu ilk versiyon ile yeni versiyonun birlikte calismasinin tehikeli oldugu durumlarda kullaniriiz.
    # RollingUpdate: Varsayilan budur. podlar sileme eklem islemlerini beraber yapar.
  template:
    metadata:
      labels:
        app: recreate
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
### Rolling
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldeployment
  labels:
    team: development
spec:
  replicas: 10
  selector:
    matchLabels:
      app: rolling
  strategy:
    type: RollingUpdate # ayni anda yeni ve eski versiyonlar beraber calisir.
    rollingUpdate:
      maxUnavailable: 2 # 2 pod silme ilk asamada.Varsayilan deger yuzde 25tir. Bu orenk icin ilk basta 8e dusecektir. Onun altina dusmez.
      maxSurge: 2 # fazladan 2 pod olusturabilir. Bu ornek icin pod sayisi 12 olarak devam eder.
  template:
    metadata:
      labels:
        app: rolling
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
### PV ve PVC baglama
apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
type: Opaque
stringData:
  password: P@ssw0rd!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldeployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql" # container icindeki klasor
              name: mysqlvolume # asagida verdigim isimle ayni olmali
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: password
      volumes:
        - name: mysqlvolume # bu ismi biz veriyoruz.
          persistentVolumeClaim:
            claimName: mysqlclaim # bu bizim olusturdugumuz PVC objectinin ismi
---
### StorageClassli ornek
apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
type: Opaque
stringData:
  password: P@ssw0rd!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldeployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysqlvolume
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: password
      volumes:
        - name: mysqlvolume
          persistentVolumeClaim:
            claimName: mysqlclaim # birdegisiklik yok. bor onceki ornek gibi