apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    team: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ozgurozturknet/k8s:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    team: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ozgurozturknet/k8s:backend
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service # tipi service
metadata:
  name: backend # bu isim onemli. VCunku cluster icinden artik bu isimle ulasacagiz bu servise.
spec:
  type: ClusterIP # servisin tipi
  selector:
    app: backend # bu onemli. baglanti kurmak icin kullanilir. podlarin label degeru app: backend olanlarla eslesir.
  ports:
    - protocol: TCP
      port: 5000  # bu servisin dinleyecegi port.
      targetPort: 5000 # podlarimizin expose ettigi port.


apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort # tip Nodeport
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # servisin dinleyecegi port
      targetPort: 80 # servisin yonlendirilecegi port

---
# Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: frontendlb
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80