FROM ubuntu:latest
WORKDIR /gecici
ARG VERSION=3.8.1
### Versiyonu daha dinamik alabiliriz.
# ADD https://www.python.org/ftp/python/3.7.6/Python-3.7.6.tgz .
ADD https://www.python.org/ftp/python/${VERSION}/Python-${VERSION}.tgz .
CMD ls -al